{% set name = "smac" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa43e38b285b7d5625fa9b5d3da2f56215d226a59c78f77081326abc356fb633

build:
  number: 0
  noarch: python
  entry_points:
    - smac = smac.smac_cli:cmd_line_call
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.7.1
    - scipy>=1.7.0
    - psutil
    - pynisher>=0.4.1
    - ConfigSpace >=0.5.0
    - joblib
    - scikit-learn >=0.22.0
    - pyrfr >=0.8.0
    - dask
    - distributed
    - emcee >=3.0.0
    - __linux

test:
  imports:
    - smac
    - smac.configspace
  commands:
    - pip check
    - smac --help
  requires:
    - pip


about:
  home: https://www.automl.org/automated-algorithm-design/algorithm-configuration/smac/
  summary: Sequential Model-based Algorithm Configuration
  description: |
    SMAC is a tool for algorithm configuration to optimize the parameters of arbitrary
    algorithms across a set of instances. This also includes hyperparameter optimization
    of ML algorithms. The main core consists of Bayesian Optimization in combination
    with an aggressive racing mechanism to efficiently decide which of two configurations
    performs better.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://automl.github.io/SMAC3/
  dev_url: https://github.com/automl/SMAC3

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
